# Generated by Django 2.2.1 on 2019-05-28 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190515_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text_fa', models.TextField()),
                ('text_en', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/posts')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text_fa', models.TextField()),
                ('text_en', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/posts')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='text',
            new_name='text_fa',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='text',
            new_name='text_fa',
        ),
        migrations.AddField(
            model_name='category',
            name='text_en',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slideritem',
            name='text_en',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slideritem',
            name='text_fa',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slideritem',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='text_en',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(blank=True, help_text='مقاله در این منو نشان داده خواهد شد.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cms.Category'),
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cms.Tag'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cms.Tag'),
        ),
    ]
