# Generated by Django 2.2.1 on 2019-10-20 19:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190715_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymembers',
            old_name='description',
            new_name='description_fa',
        ),
        migrations.RenameField(
            model_name='companymembers',
            old_name='job',
            new_name='job_fa',
        ),
        migrations.RenameField(
            model_name='companymembers',
            old_name='name',
            new_name='name_fa',
        ),
        migrations.RenameField(
            model_name='customercompanies',
            old_name='title',
            new_name='title_fa',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='description',
            new_name='description_fa',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='title',
            new_name='title_fa',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='description_fa',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='title_fa',
        ),
        migrations.RenameField(
            model_name='slideritem',
            old_name='description',
            new_name='description_fa',
        ),
        migrations.AddField(
            model_name='companymembers',
            name='description_en',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='companymembers',
            name='job_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='companymembers',
            name='name_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customercompanies',
            name='title_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_en',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='description_en',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='text_en',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_en',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_en',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_en',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='text_en',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text_en',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
