# Generated by Django 2.2.1 on 2019-05-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190528_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='published_at',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='published_at',
            new_name='published_date',
        ),
    ]
