# Generated by Django 2.2.1 on 2019-05-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190528_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_fa',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='title_fa',
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
