# Generated by Django 2.2.1 on 2019-06-14 14:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_dislike_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_fa',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_fa',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
