# Generated by Django 2.2.1 on 2019-06-06 09:18

import customersupport.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.intenum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', utils.intenum.IntEnumField(choices=[(0, 'accepted'), (1, 'in_progress'), (2, 'completed_with_errors'), (3, 'completed_successfully')], default=0, validators=[utils.intenum.IntEnumValidator(customersupport.models.TaskStateChoices)])),
                ('result', models.FileField(blank=True, null=True, upload_to='files/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_result_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
