# Generated by Django 2.2.1 on 2019-06-14 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import genomequery.models
import utils.intenum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', utils.intenum.IntEnumField(choices=[(0, 'free_daily'), (1, 'bought_by_credit'), (2, 'created_manually')], default=2, validators=[utils.intenum.IntEnumValidator(genomequery.models.QueryTypeChoices)])),
                ('price', models.IntegerField(default=2000000, help_text='unit is IRR.')),
                ('code', models.TextField()),
                ('response', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
