# Generated by Django 2.2.1 on 2019-07-15 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genomequery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queryitem',
            name='genome_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genomequery.GenomeQuery'),
        ),
        migrations.AddField(
            model_name='queryitem',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='performed_queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
