# Generated by Django 2.2.1 on 2019-06-16 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genomequery', '0003_auto_20190616_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryitem',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='performed_queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
