# Generated by Django 2.2.1 on 2019-06-16 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genomequery', '0004_auto_20190616_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryitem',
            name='performed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='performed_queries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
