# Generated by Django 2.2.1 on 2019-06-16 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('genomequery', '0006_genomequery_free_daily_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryitem',
            name='performed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
