# Generated by Django 2.2.1 on 2019-07-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
