# Generated by Django 2.2.1 on 2019-06-16 09:32

from django.db import migrations, models
import members.models
import utils.intenum


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190514_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncreaseCreditViaBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=20000000, help_text='Unit is IRR')),
                ('status', utils.intenum.IntEnumField(choices=[(0, 'success'), (1, 'failed')], default=0, validators=[utils.intenum.IntEnumValidator(members.models.IncreaseCreditViaBankChoices)])),
                ('tracking_code', models.CharField(max_length=200)),
            ],
        ),
    ]
